stages:
  - lint
  - test
  - build
  - upload


lint:
  stage: lint
  script: echo "Running linter"
    - source $TORSKEL_ENV && flake8

test:
  stage: test
  script: echo "Running tests"

build_prod:
  stage: build
  script:
    - echo "Building production package"
    - pwd


  only:
  - master



