stages:
  - lint
  - test
  - build
  - upload


lint:
  stage: lint
  script:
    - echo "Running linter"
    - source $TORSKEL_ENV && cd ./torskel && flake8



test:
  stage: test
  script:
    - echo "Running tests"

build_prod:
  stage: build
  script:
    - echo "Building production package"
    - rm -rf ./dist/*
    - rm -rf ./build/*


  only:
  - master



